### ISSUE TITLE
html文件夹没有上传

### ISSUE THREAD

**Issue by sonichy** [onlyfu/UnProxy#1]
html文件夹没有上传，弹出页面不存在。

**Comment by yuiitsu** [comment]
https://github.com/yuiitsu/UnProxy/blob/master/dist/unproxy-0.1.1.crx 解压一下

**Comment by yuiitsu** [comment]
> html文件夹没有上传，弹出页面不存在。

https://github.com/yuiitsu/UnProxy/blob/master/dist/unproxy-0.1.1.crx 解压一下
