### ISSUE TITLE
请问UnProxy接受什么样的代理？

### ISSUE THREAD

**Issue by leonsama** [onlyfu/UnProxy#4]
请问UnProxy能接受SSR吗？如果不能的话，请问怎么自己搭建一个UnProxy可以使用代理服务器？

**Comment by yuiitsu** [comment]
可以看看这个：https://github.com/yuiitsu/Article/blob/master/Other/%E5%8F%8C%E6%9C%8D%E5%8A%A1%E5%99%A8%EF%BC%8CCentOS%E7%B3%BB%E7%BB%9F%EF%BC%8C%E4%BD%BF%E7%94%A8Squid%E5%92%8CStunnel%E6%90%AD%E5%BB%BA%E7%BF%BB%E5%A2%99%E4%BB%A3%E7%90%86%E6%9C%8D%E5%8A%A1.md
